export const SELECT_PAIR = 'SELECT_PAIR';
export const CHANGE_SIDE = 'CHANGE_SIDE';
export const CHANGE_ORDER_TYPE = 'CHANGE_ORDER_TYPE';
export const CHANGE_LIMIT = 'CHANGE_LIMIT';
export const CHANGE_QUANTITY = 'CHANGE_QUANTITY';
export const ADD_ORDER = 'ADD_ORDER';